# fly.toml app configuration file generated for bold-sea-6198 on 2023-06-01T06:50:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-sea-6198"
primary_region = "mad"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[http_service]
  processes = ["app"]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  [tcp_checks]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
  [http_checks]
    interval = "15s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false