# fly.toml app configuration file generated for cold-star-519 on 2023-06-01T12:03:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-star-519"
primary_region = "mad"

[env]
  PORT = 8080 # add this

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

#[http_service]
#  processes = ["app"]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = true
#  auto_start_machines = true
#  min_machines_running = 0
#  [tcp_checks]
#    grace_period = "5s"
#    interval = "15s"
#    timeout = "2s"
#    restart_limit = 0

[[services]]
  http_checks = []
  processes=["app"]
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    timeout = "2s"
    restart_limit = 0

#  [http_checks]
#    interval = "15s"
#    grace_period = "5s"
#    method = "get"
#    path = "/health"
#    protocol = "http"
#    restart_limit = 0
#    timeout = "2s"
#    tls_skip_verify = false
#    processes=["app"]